services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        SecIT\ElasticFormBundle\ElasticForm\FieldType\TypeInterface:
            tags: [elasticform.field_type]

    SecIT\ElasticFormBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Tests,Resources}'
